### ISSUE TITLE
The `list` special case uses the expected type poorly

### ISSUE THREAD

**Issue by takikawa** [racket/typed-racket#33]
Example:

```
#lang typed/racket

(: x (U (List Symbol Any)
        (List String Symbol)))
(define x (list "foo" 'bold))
```

Produces this error message:

```
/tmp/union.rkt:5:10: Type Checker: type mismatch
  expected: (U (List Symbol Any) (List String Symbol))
  given: (List String Any)
  in: (list "foo" (quote bold))
  context...:
```

Note that using a literal list there for `x` will work.
